[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && yarn install && yarn tinacms build && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://bonsaiblu.it"
