---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
  hidden: false
- type: text
  name: discount_price
  label: discount_price
  hidden: false
- type: tag_list
  name: colors
  label: colors
- type: tag_list
  name: sizes
  label: sizes
